In [1]:
a = 1
b = 2
c = 3
d = 4

In [2]:
a+b, a-b, a*c

(3, -1, 3)

In [3]:
print(a+b)
print(a+b,a-b,a&c)

3
3 -1 1


In [6]:
print(a*b)
print(d/b)
print(d%c)

2
2.0
1


In [7]:
a = input()

 10


In [8]:
type(a)

str

In [9]:
a = float(input())

 10


In [10]:
type(a)

float

In [11]:
a=int(input())

 10


In [12]:
type(a)

int

In [13]:
a = input()

 10


In [14]:
type(a)

str

In [15]:
a=float(input())

 10


In [21]:
a=123
b=-123
c=0

In [22]:
type(a)

int

In [23]:
a=1.2
b=-2.1

In [24]:
type(b)

float

In [28]:
a=1.24e-2

In [29]:
a

0.0124

In [26]:
b=1.24E2

In [27]:
b

124.0

In [30]:
10<15

True

In [31]:
10<=5

False

In [32]:
10>61

False

In [33]:
print(bool(1))

True


In [34]:
print(bool(0))

False


In [35]:
print(())

()


In [36]:
print(bool(""))

False


In [37]:
print(bool("안녕"))

True


In [38]:
1==1

True

In [39]:
1==0

False

In [40]:
1!=1

False

In [41]:
not 1==1

False

In [42]:
1==1 and 1==2

False

In [43]:
1==1 or 1==2

True

In [44]:
"Life is too short, You need Python"

'Life is too short, You need Python'

In [45]:
"a"

'a'

In [46]:
"123"

'123'

In [47]:
food = "Python's favorite food is perl"

In [49]:
type(food)

str

In [50]:
python='python'

In [51]:
a="python"
b=2

In [52]:
a*b

'pythonpython'

In [53]:
print("="*50)
print("My Program")
print("="*50)

My Program


In [54]:
A=[1,2,3,4,5]
type(A)

list

In [56]:
a="독고영재, 50"
b="김철수, 30"
c=[a,b]

In [57]:
list = ["독고영재, 50", "김철수, 30"]

In [61]:
A = [10,20,30]
B = (10,20,30)

In [63]:
import numpy as np

In [73]:
a=np.array([1,2,3])
b=np.array([5,6,7])
c=a+b
type(c)
c.shape
c

array([ 6,  8, 10])

In [70]:
a=[1,2,3]
b=[5,6,7]
c=a+b
type(c)
c

[1, 2, 3, 5, 6, 7]

In [79]:
D=[1,2,4,"a"]
D

[1, 2, 4, 'a']

In [81]:
E=np.array(D)
E

array(['1', '2', '4', 'a'], dtype='<U21')

In [82]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
type(c)
c.shape

(2, 3)

In [83]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a.shape

(1, 3, 3)

In [84]:
#문제
#1.
list = [1,5,7,8,10,"안녕","a"]
list

[1, 5, 7, 8, 10, '안녕', 'a']

In [87]:
a = np.array([1,2,4,5])
b = np.array([2,3,5,6])
print(a+b)

[ 3  5  9 11]


In [89]:
A = np.array([[1,2,3,4,5,6],[20,19,18,17,16,15]])
A

array([[ 1,  2,  3,  4,  5,  6],
       [20, 19, 18, 17, 16, 15]])

In [ ]:
print("-"*10)
print("데이터전처리 수업")
print("끝")
print("